import { Loader } from "@mantine/core";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import { api } from "~/utils/api";

export default function Home() {
  const [links, setLinks] = useState<{ name: string; url: string }[]>([]);
  useEffect(() => {
    setLinks([
      {
        name: "Spotify",
        url: "https://open.spotify.com/artist/61SB4Zoq6xmsImJQoxUDk3?si=JFzCJt3dTTaTbB2cmjdsnQ",
      },
      {
        name: "Bandcamp (new releases earlier than spotify)",
        url: "https://safetybreak.bandcamp.com/",
      },
      {
        name: "Soundcloud (for live recordings)",
        url: "https://soundcloud.com/safety-break",
      },
      {
        name: "Youtube",
        url: "https://www.youtube.com/@safetybreakroc",
      },
      {
        name: "Booking Email",
        url: "mailto:safetybreakroc@gmail.com",
      },
    ]);
  }, []);
  return (
    <>
      <Head>
        <title>Safety Break</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gradient-top">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Safety <span className="text-[hsl(280,100%,70%)]">Break</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <section
            // className={utilStyles.headingMd}
            >
              <p>
                {links?.length > 0 ? (
                  <ul
                  //  className={utilStyles.list}
                  >
                    {links.map(({ name, url }) => (
                      <li
                        // className={classnames([
                        //   utilStyles.listItem,
                        //   utilStyles.moveOnHover,
                        // ])}
                        key={name}
                      >
                        <Link
                          className="my-3 flex max-w-xs flex-col gap-4 rounded-xl nyanza-bg p-4 dogwood text-white hover:bg-white/20"
                          href={url}
                          target="_blank"
                        >
                          <h3 className="text-2xl font-bold">{name} →</h3>
                        </Link>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <Loader />
                )}
              </p>
            </section>

            <div className="flex flex-col items-center gap-2">
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <>
      <div className="flex flex-col items-center justify-center gap-4">
        <p className="text-center text-2xl text-white">
          {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
          {/* {secretMessage && <span> - {secretMessage}</span>} */}
        </p>
        <button
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          onClick={sessionData ? () => void signOut() : () => void signIn()}
        >
          {sessionData ? "Sign out" : "Sign in"}
        </button>
      </div>
    </>
  );
}
